# Base Image
FROM nexus.meatbox.co.kr/prod/base/meatbox-web:latest

# 포트 설정
EXPOSE 17100

# 권한 설정
RUN chmod u+x $CATALINA_HOME/bin/catalina.sh \
    # 이미지 서버 마운트 경로 생성
    && mkdir -p /home/DATA/www-deploy/meatbox-web2/src/main \
    # 디렉토리 소유권 설정
    && chown www:www -R /home/DATA/ /usr/local/tomcat/ /usr/lib/jvm

# 사용자 변경
USER www

# Tomcat 설정 파일 복사
COPY --chown=www tomcat-dev/conf/. $CATALINA_HOME/conf/ 
COPY --chown=www tomcat-dev/bin/. $CATALINA_HOME/bin/

# 애플리케이션 배포
COPY --chown=www src/main/. /home/DATA/www-deploy/meatbox-web2/src/main/

# Tomcat 서버 실행
ENTRYPOINT ["sh", "-c", "entry.sh"]