version: "3.9"

services:
  meatbox:
    image: nexus.meatbox.co.kr/dev/meatbox/web:latest
    hostname: '{{.Service.Name}}-{{.Task.Slot}}'
    environment:
      NODE_HOSTNAME: '{{.Node.Hostname}}'
      TASK_ID: '{{.Task.ID}}'
      TASK_NAME: '{{.Task.Name}}'
    ports:
      - target: 17100
        published: 8182
        protocol: tcp
        mode: ingress
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
        preferences:
          - spread: node.labels.hostname
      labels:
        - app=meatbox-web
        - env=dev
        - swarmpit.service.deployment.autoredeploy=false
      resources:
        limits:
          cpus: "2"
          memory: 8192M
        reservations:
          cpus: "1"
          memory: 4096M
      restart_policy:
        condition: any
        delay: 10s
        max_attempts: 3
        window: 60s
      update_config:
        delay: 10s
        order: start-first
      rollback_config:
        delay: 10s
        order: start-first
    volumes:
      - meatbox-web-image-server-dev-50:/home/DATA/share/meatbox
      - type: bind
        source: /home/super/docker/logs/web
        target: /usr/local/tomcat/tomcat-meatbox-web2/logs
        read_only: false
    networks:
      - meatbox-web
    secrets:
      - source: MeatboxSecretKey
        target: /home/DATA/www-deploy/meatbox-web2/src/main/webapp/WEB-INF/classes/properties/MeatboxSecretKey.properties
    #entrypoint: ["sh", "-c", "entry.sh"]
    healthcheck:
      test: ["CMD", "/bin/sh", "/usr/local/tomcat/tomcat-meatbox-web2/bin/health_check.sh", "17100"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  meatbox-web:
    driver: overlay

volumes:
  meatbox-web-image-server-dev-50:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.2.50,vers=4.2,soft
      device: :/data/share/meatbox

secrets:
  MeatboxSecretKey:
    external: true
